### ISSUE TITLE
Xcode 9 

### ISSUE THREAD

**Issue by iworkinprogress** [bitstadium/HockeySDK-tvOS#15] opened 2017-06-26 16:26 UTC
Xcode 9 cannot compile a tvOS app with the Hockey tvOS SDK.

In `BTHockeyManager.h` line 259:
`HOCKEYSDK_FEATURE_STORE_UPDATES_ is not defined, evaluates to 0.`

Should that line be:
`#ifdef HOCKEYSDK_FEATURE_STORE_UPDATES`

instead of: 
`#if HOCKEYSDK_FEATURE_STORE_UPDATES`

**Comment by ElektrojungeAtWork** [comment] 2017-06-26 16:44
Hey Stephen,
Thx for getting in touch.

I replied to you in support already, but I thought that I'd post here, too, so other folks can see my response.

We've released a new version of the iOS SDK last week, and tvOS and macOS are up next. I'll make sure it's possible to use the SDK with Xcode 9 and the new tvOS SDK.

Thx for using HockeyApp!!!

**Comment by ElektrojungeAtWork** [comment] 2017-07-07 19:51
Hi Stephen,

You mentioned in support that you are integrating the SDK as binaries. I can't reproduce the issue you are seeing here. I've attached [ a simple sample project](https://github.com/bitstadium/HockeySDK-tvOS/files/1132133/HockeyAppTvOSTesting.zip). Would you mind trying to compile that one?
If that project works for you but your app continues to see the compile error, I suspect that your project setup is different. In this case, I'd love to have a sample project that has that issue.
Please also share your integration code with me. If you don't want to have our conversation here, please reply to me in the HockeyApp Support. Thx!

Benny

**Comment by iworkinprogress** [comment] 2017-07-14 16:16
Hi Benny,

Our app is written in Objective-C and has treat warnings as errors set to true.

I was able to duplicate in your sample app by adding an Objective-C target and setting 'Treat warnings as errors' to true. 
[HockeyAppTvOSTesting-objc.zip](https://github.com/bitstadium/HockeySDK-tvOS/files/1149023/HockeyAppTvOSTesting-objc.zip)

**Comment by ElektrojungeAtWork** [comment] 2017-07-15 02:03
Hi Steven,

thanks for the test project. I've made a few changes. Would you mind testing once more with the sample project that I've attached this time? It's an ObjC app for tvOS and uses `treat warnings as errors` and enables `-wEverything` minus a few exceptions that are not THAT important to care about.
The project compiles in Xcode 9 beta 3 without warnings here.

Thanks for helping! I really appreciate it.

Let me know how it goes this time. Feel free to test the binaries that are part of the sample project in your own app.

Cheers & have a good weekend!
Benny
[HockeyTvOSObjCTesting.zip](https://github.com/bitstadium/HockeySDK-tvOS/files/1149994/HockeyTvOSObjCTesting.zip)

**Comment by iworkinprogress** [comment] 2017-07-17 19:15
:+1: Compiles now in my app as well.

**Comment by ElektrojungeAtWork** [comment] 2017-07-18 19:11
@iworkinprogress great! 

Did I mention that you're awesome!? Customers like you make my day. Now, off to hit that release button! ^^

**Comment by ElektrojungeAtWork** [comment] 2017-07-19 01:12
4.1.2 of the SDK is out. Closing this issue. =)

**Closed as completed by ElektrojungeAtWork** 2017-07-19 01:12 UTC
